# Generated by Django 5.2 on 2025-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_order_bookings_or_paycom__5f6c32_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('confirmed', 'Подтвержден/Активен'), ('completed', 'Завершен/Использован'), ('cancelled_user', 'Отменен пользователем'), ('cancelled_admin', 'Отменен системой/администратором'), ('payment_failed', 'Ошибка оплаты'), ('expired_awaiting_payment', 'Истекло время ожидания оплаты'), ('refund_initiated', 'Возврат инициирован'), ('refunded', 'Возвращено')], db_index=True, default='pending_payment', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('awaiting_checkout_redirect', 'Ожидание перехода к оплате'), ('provider_processing', 'Обработка платежным провайдером'), ('provider_payment_succeeded', 'Оплата успешна (у провайдера)'), ('provider_payment_failed', 'Ошибка оплаты (у провайдера)'), ('provider_session_expired', 'Истекло время сессии оплаты (у провайдера)'), ('order_created_successfully', 'Заказ успешно подтвержден'), ('order_creation_failed', 'Ошибка подтверждения заказа (после оплаты)'), ('refund_processing', 'Обработка возврата'), ('refunded', 'Возвращено')], db_index=True, default='awaiting_checkout_redirect', max_length=35, verbose_name='Статус транзакции'),
        ),
    ]
